name: fix_webrtc
description: Fix WebRTC
version: 0.0.1

environment:
  sdk: ^2.12.0
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.seoiclick.fixwebrtc
        pluginClass: FixWebrtcPlugin
      ios:
        pluginClass: FixWebrtcPlugin